name: Checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 20"
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: "Setup npm" # Add our registry to npm config
        run: | # Custom action
          npm set @thiendang:registry=https://npm.pkg.github.com/thiendang
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npx lerna exec npm run test
